#!/usr/bin/env node
// assemble.mjs - generate spec/product.md as a faithful aggregate of the per-feature specs.
//
// Per-feature spec.md files are CANONICAL. product.md is GENERATED and must never be hand-edited.
// Output is a pure function of the inputs (no timestamps), so `--check` is a clean equality test.
//
// Usage:
//   node scripts/assemble.mjs [--root <specDir>]   # regenerate and WRITE <root>/product.md
//   node scripts/assemble.mjs --check [--root ...]  # verify on-disk product.md is current (no write)
//
// Exit codes: 0 ok / up-to-date · 1 stale or missing (--check) · 2 hard error.
// Runtime: Node >=18, zero dependencies, cross-platform.

import { readFileSync, existsSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

const args = process.argv.slice(2)
const check = args.includes('--check')
const rootIdx = args.indexOf('--root')
const root = rootIdx !== -1 && args[rootIdx + 1] ? args[rootIdx + 1] : 'spec'

const warn = (m) => process.stderr.write(`assemble: warn: ${m}\n`)
const fail = (m) => { process.stderr.write(`assemble: error: ${m}\n`); process.exit(2) }

const hash = (buf) => 'sha256:' + createHash('sha256').update(buf).digest('hex').slice(0, 12)
const readUtf8 = (p) => readFileSync(p, 'utf8')
const trimEnd = (s) => s.replace(/\s+$/, '')

// Minimal, dependency-free frontmatter scalar reader: pulls top-level (zero-indent) `key: value`
// pairs from the first `---`-fenced block. Nested (indented) keys like readiness/gate are ignored.
function frontmatterScalars(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/)
  if (!m) return null
  const out = {}
  for (const line of m[1].split(/\r?\n/)) {
    const mm = line.match(/^([A-Za-z_][\w-]*):[ \t]*(.*)$/) // zero-indent only
    if (!mm) continue
    const lead = mm[2].replace(/^[ \t]+/, '')
    let v
    if (lead[0] === '"' || lead[0] === "'") {
      const q = lead[0]
      const end = lead.indexOf(q, 1)
      v = end === -1 ? lead.slice(1) : lead.slice(1, end) // quoted: literal, ignore any trailing comment
    } else {
      v = lead.replace(/\s+#.*$/, '').trim() // unquoted: strip a trailing ` # comment`
    }
    out[mm[1]] = v
  }
  return out
}

function loadFeatures(featuresDir) {
  if (!existsSync(featuresDir)) return []
  const slugs = readdirSync(featuresDir).filter((d) => {
    try { return statSync(join(featuresDir, d)).isDirectory() } catch { return false }
  })
  const features = []
  for (const slug of slugs) {
    const manifestPath = join(featuresDir, slug, 'feature.md')
    if (!existsSync(manifestPath)) { warn(`features/${slug}/ has no feature.md - skipping`); continue }
    const fm = frontmatterScalars(readUtf8(manifestPath))
    if (!fm) fail(`features/${slug}/feature.md has no YAML frontmatter`)
    for (const req of ['id', 'slug', 'status']) {
      if (!fm[req]) fail(`features/${slug}/feature.md missing required field: ${req}`)
    }
    if (!fm.title) { warn(`features/${slug}/feature.md missing title - defaulting to slug`); fm.title = fm.slug }
    if (!['active', 'done', 'dropped'].includes(fm.status)) {
      fail(`features/${slug}/feature.md has invalid status: ${fm.status}`)
    }
    if (fm.status === 'dropped') continue // excluded from the aggregate
    const specPath = join(featuresDir, slug, 'spec.md')
    if (!existsSync(specPath)) { warn(`features/${slug}/ (status ${fm.status}) has no spec.md yet - skipping`); continue }
    features.push({ id: fm.id, slug: fm.slug, title: fm.title, spec: readUtf8(specPath) })
  }
  // Deterministic order by immutable id.
  features.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
  return features
}

function build() {
  const globalPath = join(root, 'product-global.md')
  let global = ''
  if (existsSync(globalPath)) global = readUtf8(globalPath)
  else warn(`${globalPath} not found - treating product-global as empty`)

  const features = loadFeatures(join(root, 'features'))

  const provenance = [
    '<!-- provenance (generated - do not edit)',
    `productGlobalHash: ${hash(global)}`,
    'features:',
    ...features.map((f) => `  ${f.id} ${f.slug} ${hash(f.spec)}`),
    '-->',
  ].join('\n')

  const blocks = [
    '<!-- GENERATED by assemble.mjs - DO NOT EDIT. Edit feature specs (spec/features/<slug>/spec.md). -->',
    '# Product',
    provenance,
    '## Product-global',
    trimEnd(global),
    ...features.map((f) => `## Feature: ${f.id} - ${f.title}\n\n${trimEnd(f.spec)}`),
  ]
  return blocks.map(trimEnd).join('\n\n') + '\n'
}

const outPath = join(root, 'product.md')
let assembled
try { assembled = build() } catch (e) { fail(e && e.message ? e.message : String(e)) }

if (check) {
  if (!existsSync(outPath)) { process.stderr.write(`assemble: ${outPath} is missing - run assemble to generate it\n`); process.exit(1) }
  const current = readUtf8(outPath)
  if (current === assembled) { process.stdout.write(`assemble: ${outPath} is up to date\n`); process.exit(0) }
  process.stderr.write(`assemble: ${outPath} is STALE - feature specs have changed since it was generated\n`)
  process.exit(1)
} else {
  writeFileSync(outPath, assembled)
  process.stdout.write(`assemble: wrote ${outPath}\n`)
  process.exit(0)
}
